### ISSUE TITLE
Error from Milter

### ISSUE THREAD

**Issue by paulbraxton3** [lmco/laikaboss#48]
All seems to be up and running correctly, laikad, worker, broker, milter all on one box. A simple test email from command line to postfix the message is passed to milter, then I get this error:

Sep 19 08:59:56 hostname laikamilter: 0002f3446bf5 ERROR EOM: RETURNING DEFAULT (0)   ['Traceback (most recent call last):\n', '  File "/var/opt/laika/laikaboss-master/milter/laikamilter.py", line 290, in eom\n    self.rtnToMTA = self._dispositionMessage()\n', '  File "/var/opt/laika/laikaboss-master/milter/laikamilter.py", line 395, in _dispositionMessage\n    success = dispositioner.zmqGetFlagswithRetry(self.milterConfig.zmqMaxRetry, self)\n', '  File "/var/opt/laika/laikaboss-master/milter/laikamilter.py", line 588, in zmqGetFlagswithRetry\n    sendResponse = self._zmqGetFlags(numRetries, milterContext)\n', '  File "/var/opt/laika/laikaboss-master/milter/laikamilter.py", line 616, in _zmqGetFlags\n    gotResponseFromScanner = self._zmqSendBuffer(milterContext, numRetries, REQUEST_TIMEOUT, SERVER_ENDPOINT)\n', '  File "/var/opt/laika/laikaboss-master/milter/laikamilter.py", line 636, in _zmqSendBuffer\n    source=milterContext.milterConfig.milterName+"-"+str(myhostname[:myhostname.index(".")]),\n', 'ValueError: substring not found\n']

**Comment by marnao** [comment]
this will be addressed in a future commit -- but to anyone who wants a fix sooner, this assumes you have a hostname with at least one period. bad assumption.
