### ISSUE TITLE
Run error 

### ISSUE THREAD

**Issue by ctyk3322** [lmco/laikaboss#73]
I might be overlooking something simple, but I get the following error when trying to run Laikaboss as a standalone mode. 

[c@localhost laikaboss]$ ./laika.py badness.exe
ERROR:root:error on f3279c32-c38a-4f55-8dbc-49b502b6434e running module META_EXIFTOOL. exception details below: 
Traceback (most recent call last):
  File "/home/c/laikaboss/laikaboss/si_module.py", line 43, in run
    moduleResult = self._run(scanObject, result, depth, args)
  File "/home/c/laikaboss/laikaboss/modules/meta_exiftool.py", line 45, in _run
    with exiftool.ExifTool() as et:
  File "/usr/lib/python2.7/site-packages/exiftool.py", line 191, in __enter__
    self.start()
  File "/usr/lib/python2.7/site-packages/exiftool.py", line 174, in start
    stderr=devnull)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ctyk3322** [comment]
Never mind, it looks like I forgot to install the exiftool itself.
